import Head from 'next/head';
import { useEffect, useState } from 'react';
import ContentLoader from 'react-content-loader';
import Container from '../components/Container';
import NotebookList from '../components/NotebookList';
import Api from './api/api.utils';
import Spacer from '../components/Spacer';
import { Button } from '../components/Button';

export default function Home() {
  const [notebooks, setNotebooks] = useState([]);
  const [loading, setLoading] = useState(true);

  const listNotebooks = async () => {
    const data = await Api.getAll();
    setNotebooks(data);
    setLoading(false);
  };

  useEffect(() => {
    listNotebooks();

    // const subscription = subscribeNotebooks((newNotebook) => {
    //   setNotebooks((currentNotebookList) => {
    //     return [newNotebook, ...currentNotebookList];
    //   });
    // });

    // return () => {
    //   subscription.unsubscribe();
    // };
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <NotebookList notebooks={notebooks} />
          {loading && <Skeleton />}
          {!loading && (
            <>
              <Spacer vertical={16} />
              <Button
                label="Adicionar caderno"
                color="primary"
                shape="regularMD"
              />
            </>
          )}
        </Container>
      </main>
    </div>
  );
}

const Skeleton = () => {
  return (
    <ContentLoader
      style={{
        width: '100%',
        height: '44px',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <rect x="0" y="0" rx="4" ry="4" width="100%" height="44" />
    </ContentLoader>
  );
};
