import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import Container from '../components/Container';
import NotebookList from '../components/NotebookList';
import { getNotebooks, subscribeNotebooks } from '../supabase';

export default function Home() {
  const [notebooks, setNotebooks] = useState([]);

  const listNotebooks = async () => {
    const data = await getNotebooks();
    setNotebooks(data);
  };

  useEffect(() => {
    listNotebooks();

    const subscription = subscribeNotebooks((newNotebook) => {
      setNotebooks((currentNotebookList) => {
        return [newNotebook, ...currentNotebookList];
      });
    });

    return () => {
      subscription.unsubscribe();
    };
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <NotebookList notebooks={notebooks} />
        </Container>
      </main>

      <footer>Footer</footer>
    </div>
  );
}
